import type { Abi } from "viem";

export const rugBountyVaultAbi = [
  {
    type: "function",
    name: "createBond",
    stateMutability: "payable",
    inputs: [
      { name: "token", type: "address" },
      { name: "launchTxHash", type: "bytes32" },
      { name: "launchTimestamp", type: "uint256" },
      { name: "declaredCreatorWallets", type: "address[]" },
      { name: "declaredRetainedBalance", type: "uint256" },
      { name: "oathText", type: "string" },
      { name: "rulesHash", type: "bytes32" },
      { name: "expiresAt", type: "uint256" },
    ],
    outputs: [{ name: "bondId", type: "uint256" }],
  },
  {
    type: "function",
    name: "flagBreach",
    stateMutability: "nonpayable",
    inputs: [{ name: "bondId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "resolveBond",
    stateMutability: "nonpayable",
    inputs: [{ name: "bondId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "refundAfterExpiry",
    stateMutability: "nonpayable",
    inputs: [{ name: "bondId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "getBond",
    stateMutability: "view",
    inputs: [{ name: "bondId", type: "uint256" }],
    outputs: [
      {
        type: "tuple",
        components: [
          { name: "creator", type: "address" },
          { name: "token", type: "address" },
          { name: "launchTxHash", type: "bytes32" },
          { name: "launchTimestamp", type: "uint256" },
          { name: "declaredCreatorWallets", type: "address[]" },
          { name: "declaredRetainedBalance", type: "uint256" },
          { name: "bondAmount", type: "uint256" },
          { name: "createdAt", type: "uint256" },
          { name: "expiresAt", type: "uint256" },
          { name: "oathHash", type: "bytes32" },
          { name: "rulesHash", type: "bytes32" },
          { name: "breachObserved", type: "bool" },
          { name: "status", type: "uint8" },
          { name: "slashedTo", type: "address" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "currentCreatorBalance",
    stateMutability: "view",
    inputs: [{ name: "bondId", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "nextBondId",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "event",
    name: "BondCreated",
    anonymous: false,
    inputs: [
      { indexed: true, name: "bondId", type: "uint256" },
      { indexed: true, name: "creator", type: "address" },
      { indexed: true, name: "token", type: "address" },
      { indexed: false, name: "launchTxHash", type: "bytes32" },
      { indexed: false, name: "launchTimestamp", type: "uint256" },
      { indexed: false, name: "declaredCreatorWallets", type: "address[]" },
      { indexed: false, name: "declaredRetainedBalance", type: "uint256" },
      { indexed: false, name: "bondAmount", type: "uint256" },
      { indexed: false, name: "expiresAt", type: "uint256" },
      { indexed: false, name: "oathText", type: "string" },
      { indexed: false, name: "oathHash", type: "bytes32" },
      { indexed: false, name: "rulesHash", type: "bytes32" },
    ],
  },
  {
    type: "event",
    name: "BondBreachFlagged",
    anonymous: false,
    inputs: [
      { indexed: true, name: "bondId", type: "uint256" },
      { indexed: true, name: "observer", type: "address" },
      { indexed: false, name: "currentBalance", type: "uint256" },
      { indexed: false, name: "declaredRetainedBalance", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "BondSlashed",
    anonymous: false,
    inputs: [
      { indexed: true, name: "bondId", type: "uint256" },
      { indexed: true, name: "hunter", type: "address" },
      { indexed: false, name: "hunterPayout", type: "uint256" },
      { indexed: false, name: "protocolPayout", type: "uint256" },
      { indexed: false, name: "currentBalance", type: "uint256" },
      { indexed: false, name: "declaredRetainedBalance", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "BondRefunded",
    anonymous: false,
    inputs: [
      { indexed: true, name: "bondId", type: "uint256" },
      { indexed: true, name: "creator", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
  },
] as const satisfies Abi;
